# Generated by Django 6.0.4 on 2026-04-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_chamado_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='prioridade',
            field=models.BooleanField(default=False, verbose_name='É Prioridade?'),
        ),
    ]
